"""Extend execution logs with vision audit columns

Revision ID: 064c60228372
Revises: 631dca769e63
Create Date: 2026-07-17 17:53:38.527895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064c60228372'
down_revision: Union[str, Sequence[str], None] = '631dca769e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_execution_logs', sa.Column('image_filename', sa.String(length=255), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('image_width', sa.Integer(), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('image_height', sa.Integer(), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('vision_confidence', sa.Float(), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('detected_hazards', sa.JSON(), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('contamination_level', sa.String(length=50), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('analysis_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_execution_logs', 'analysis_model')
    op.drop_column('agent_execution_logs', 'contamination_level')
    op.drop_column('agent_execution_logs', 'detected_hazards')
    op.drop_column('agent_execution_logs', 'vision_confidence')
    op.drop_column('agent_execution_logs', 'file_size')
    op.drop_column('agent_execution_logs', 'mime_type')
    op.drop_column('agent_execution_logs', 'image_height')
    op.drop_column('agent_execution_logs', 'image_width')
    op.drop_column('agent_execution_logs', 'image_filename')
    # ### end Alembic commands ###
