"""Extend execution logs with audit columns

Revision ID: 631dca769e63
Revises: d8e2379306a6
Create Date: 2026-07-17 17:45:56.723748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631dca769e63'
down_revision: Union[str, Sequence[str], None] = 'd8e2379306a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_execution_logs', sa.Column('water_score', sa.Float(), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('graph_version', sa.String(length=50), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('gemini_model', sa.String(length=100), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('reflection_iterations', sa.Integer(), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('agents_executed', sa.JSON(), nullable=True))
    op.add_column('agent_execution_logs', sa.Column('synthesized_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_execution_logs', 'synthesized_response')
    op.drop_column('agent_execution_logs', 'agents_executed')
    op.drop_column('agent_execution_logs', 'reflection_iterations')
    op.drop_column('agent_execution_logs', 'gemini_model')
    op.drop_column('agent_execution_logs', 'graph_version')
    op.drop_column('agent_execution_logs', 'confidence_score')
    op.drop_column('agent_execution_logs', 'water_score')
    # ### end Alembic commands ###
