"""remove redundant auth fields for supabase

Revision ID: 971f7a30b99f
Revises: c4c2afeab9e7
Create Date: 2026-07-19 22:49:55.469099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971f7a30b99f'
down_revision: Union[str, Sequence[str], None] = 'c4c2afeab9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'refresh_token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hash', sa.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
