"""Add authentication and report export fields

Revision ID: c4c2afeab9e7
Revises: 064c60228372
Create Date: 2026-07-17 21:02:51.303713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c2afeab9e7'
down_revision: Union[str, Sequence[str], None] = '064c60228372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns natively (SQLite supports ADD COLUMN natively)
    op.add_column('reports', sa.Column('agent_execution_log_id', sa.String(length=36), nullable=True))
    op.add_column('reports', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('reports', sa.Column('markdown_path', sa.String(length=512), nullable=True))
    op.add_column('reports', sa.Column('json_path', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))

    # Batch alter only for altering existing constraint nullability
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('pdf_path',
                   existing_type=sa.VARCHAR(length=512),
                   nullable=True)
        batch_op.alter_column('summary',
                   existing_type=sa.TEXT(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_hash')
    op.drop_column('users', 'hashed_password')
    op.drop_column('reports', 'json_path')
    op.drop_column('reports', 'markdown_path')
    op.drop_column('reports', 'title')
    op.drop_column('reports', 'agent_execution_log_id')
    
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('summary',
                   existing_type=sa.TEXT(),
                   nullable=False)
        batch_op.alter_column('pdf_path',
                   existing_type=sa.VARCHAR(length=512),
                   nullable=False)
    # ### end Alembic commands ###
