import React from 'react';

const Reports = () => {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-extrabold text-white tracking-tight">Report Hub</h2>
        <p className="text-slate-400 mt-1">Download and print professional water safety reports generated by the platform.</p>
      </div>

      <div className="p-6 bg-slate-900/60 rounded-2xl border border-slate-800 space-y-6">
        <h3 className="text-lg font-bold text-white">Report Archives</h3>
        <div className="divide-y divide-slate-800">
          <div className="py-4 flex justify-between items-center gap-4">
            <div>
              <h4 className="text-sm font-semibold text-white">General Tap Water Report #1</h4>
              <p className="text-xs text-slate-500 mt-0.5">Generated on 2026-07-17 • TDS: 250 mg/L, pH: 7.2</p>
            </div>
            <a 
              href="http://localhost:8000/api/v1/reports/download/report-1" 
              className="px-4 py-2 bg-slate-800 text-slate-200 text-xs font-semibold rounded-lg hover:bg-slate-700 transition"
              download
            >
              Download PDF
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
